name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: swift package init
    - name: Build
      run: swift build -v
      
    - name: Init
      run: swift package init
    - name: Run tests
      run: swift test -v
